plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.module'
    compileSdk 34 // 可以根据需要修改

    defaultConfig {
        applicationId "com.example.module"
        minSdkVersion 31
        targetSdkVersion 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    lint {
        checkReleaseBuilds false
    }

    dependenciesInfo.includeInApk false
}

dependencies {
    compileOnly 'androidx.annotation:annotation:1.9.1'
    compileOnly 'io.github.libxposed:api:101' // API 101
    // compat 层仅供 legacy/API100 桥接使用，纯 API101 模块不需要
}
